lsi: false
highlighter: rouge
markdown: redcarpet
permalink: /blog/:title/
keep_files: [public]
exclude: [src, lib, node_modules, bower.json, Gemfile, gulpfile.js, package.json, README.md]
redcarpet:
  extensions: [smart]
